---
title: "In-class Ex5"
author: "Jayexx Low"
date: "May 11, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

### Installing & loading required libraries

The code chunk below installs and launches the tidyverse, ggdist, ggridges, colourspace & ggthemes packages into R environment

```{r}
pacman:: p_load(tidyverse, readtext, tidytext, quanteda)
```

### Importing the data

The code chunk below imports exam_data.csv into R environment by using read_csv() function of readr package, which is part of the tidyverse package.

```{r}
text_data <- readtext("data/articles/*")
``` 

```{R}
corpus_text <- corpus(text_data)
summary(corpus_text,5)
```

```{r}
usenet_words <- text_data %>%
  unnest_tokens(word, text) %>%
  filter(str_detect(word,"[a-z']$"),
         !word %in% stop_words$word)
```


```{r}
usenet_words %>%
  count(word,sort=TRUE)
```
```{R}
text_data_splitted <- text_data %>%
  separate_wider_delim("doc_id",
                       delim = "__0__",
                       names = c("X", "Y"),
                       too_few = "align_end")
```




