---
title: "The Proposal"
author: "Jayexx, Fudi, Fishgrey"
date: "May 15, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# Group Project proposal

## Project Overview

### Topic Selection & Introduction

With the given choices based on the VAST Challenge 2024 and CHINAVIS 2024 Data Visualisation Competition, the selected topic for this group project is Challenge I from the latter, titled「Data Analysis Inspires Wisdom」Time-Series Multivariate Education Data Visual Analytics Challenge . This topic was chosen due to the to the Project Group members' contextual familiarity with the topic, as well as its alignment the members' learning interests in leveraging on key visual analytics tools, to explore and design data-driven solutions for seemingly complex problems.

The selected project is centred on the learning patterns of learners in a programming course conducted by NorthClass Education Training Institute. Fundamentally, the project's raison d'etre is to provide actionable insights towards the institution's endeavor to diagnose and analyze learners' knowledge mastery levels, monitor the trends in their learning behaviors, identify and dissect potential factors that contribute to learning difficulties, and hence to derive feasible suggestions to adjust teaching strategies and course design.

To this end, data was collected from a select group of learners over a specified set of programming tasks over a particular learning period to facilitate the design and implementation of a Visual Analytics solution as a key outcome in this project.

### Problem Statement & Requirements

From the Challenge, the key problem statement was to perform a comprehensive analysis of multiple datasets that describe various aspects of the learner's profile, learning patterns and status, to derive key insights to enhance teaching strategies and course design.

Consequently the key requirements based on the 5 stipulated tasks in the challenges were as follows.

-   Task 1: to provide a quantitative assessment of the learners' knowledge mastery and identify weak links in their knowledge system, based on the multi-dimensional attributes such as answer scores and answer status in the learners' log records of the learners' question-answering behaviors.
    -   This would entail an analysis of the aggregate performance of the learners in their programming tasks, including measures of central tendency, or any notable patterns that can glean insights towards knowledge mastery and weaknesses from the given dataset
-   Task 2: Mine personalized learning behavior patterns based on learners' characteristics, and design and present learners' profiles from various perspectives, including peak answering hours, preferred question types, correct answering rates, etc.
    -   This would entail an analysis of 
-   Task 3: Different learning modes directly impact learners' ability to absorb, integrate, and apply knowledge. Efficient learning modes can enhance deep understanding and long-term memory retention of knowledge. Please model the potential relationship between learning modes and knowledge acquisition, present the results in the form of a graph, and provide a brief analysis.
    -   This would entail....
-   Task 4: The difficulty level of questions should align with the learner's level of knowledge. When a learner possesses a high level of knowledge but achieves a low percentage of correct answers, it indicates that the question's difficulty exceeds their ability. Please utilize Visual Analytics to identify these inappropriate questions.
    -   This would entail....
-   Task 5: Based on the outcomes of the aforementioned analysis, it is crucial to offer valuable recommendations for topic designers and course managers to optimize question bank content settings and enhance the quality of teaching and learning. Please briefly explain the rationale behind these suggestions.
    -   This would entail....

## The Dataset

The provided materials for included 3 datasets described below, as well as a data description document

-   Dataset 1: Student Information - This comprises of...
-   Dataset 2: Learning Subject Title Information - This comprises of...
-   Dataset 3: Class Submission Records - This comprises of...

## Approach

The broad approach for the project is shown in the figure below.

.....Insert xmind diagram here......

## Methodology

Our methodology systematically integrates data collection, data processing, analysis, pattern mining, modeling, and recommendation to create a comprehensive Visual Analytics solution for improving teaching strategies and course designs at NorthClass.

### Key Data Preparation

Based on initial assessment of the datasets, the Key Data preparation steps required are as follows.

-   .......
-   ...... Firstly, it focus on data collection and data processing, ensuring consistency in data records. Remove duplicates, handle missing values through imputation or deletion, and correct inconsistencies. Create new relevant attributes if needed.

### Key Data Viz

To address the aforesaid requirements, the envisioned DataViz for this project will be as as follows.

-   ......
-   ...... Secondly., the analysis of answering behaviors involves identifying key performance metrics such as average scores, answer correctness, and time correlations to evaluate learners' understanding and application of knowledge. Descriptive statistics will be used to compute mean, median, and mode of scores for different topics and question types. Correlation analysis will be applied to study the relationship between time taken to answer and correctness. Histograms and box plots could be used to visualize score distributions. Performance metrics could be caculated such as accuracy rate, average attempts per question, and time efficiency.

Thirdly, learning behavior patterns involve analyzing habitual actions. In preference analysis, time-series analysis will be used to identify peak answering times, analysing the frequency and performance of different question types by bar charts and pie charts to get the preferred question type. To cluster the learner group and segment profile, clustering algorithms like K-means or hierarchical clustering can be used based on behavior patterns.

Furthermore, in modeling the relationship between learning modes and knowledge acquisition, basic analysis on feature selection, standardization, correlation analysis, and descriptive analysis will be conducted to define knowledge acquisition. Linear or logistic regression models can be used to predict knowledge acquisition based on learning modes. Integrate results from different models to enhance predictive accuracy and interpret the results to provide insights.

To identify difficulties based on learner knowledge levels, difficulty and knowledge levels will be categorized based on the historical performance data, and thresholds will be defined to filter data. Filter and analyze data to detect inappropriate questions that are too difficult or too easy based on learner performance.

Last but not least, based on the output, actionable recommendations will be provided, aiming to optimize the question bank, align difficulty levels with learners' abilities, and enhance the overall quality of teaching and learning.
