project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Ex"
      menu:
      - text: "Hands-on Ex 1- Layered Grammar of Graphics: ggplot2 methods"
        href: "Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html"
      - text: "Hands-on Ex 2- Beyond ggplot2 Fundamentals"
        href: "Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html"
      - text: "Hands-on Ex 3a- Programming Interactive Data Visualisation with R"
        href: "Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3a.html"
      - text: "Hands-on Ex 3b- Programming Animated Statistical Graphics with R"
        href: "Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3b.html"
      - text: "Hands-on Ex 4a- Visual Statistical Analysis"
        href: "Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4a.html"
      - text: "Hands-on Ex 4b- Visualising Uncertainty"
        href: "Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4b.html"
      - text: "Hands-on Ex 4c- Building Funnel Plot with R"
        href: "Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4c.html"
      - text: "Hands-on Ex 5- Visualising and Analysing Text Data"
        href: "Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.html"
      - text: "Hands-on Ex 6- Modelling, Visualising and Analysing Network Data with R"
        href: "Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html"
      - text: "Hands-on Ex 7- Visualising and Analysing Time-oriented Data"
        href: "Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7.html"
      - text: "Hands-on Ex 8a- Choropleth Mapping in R"
        href: "Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8a.html"
      - text: "Hands-on Ex 8b- Visualising Geospatial Point Data"
        href: "Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8b.html"
      - text: "Hands-on Ex 8c- Analytical Mapping"
        href: "Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8c.html"
      - text: "Hands-on Ex 9a- Building Ternary Plot with R"
        href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9a.html"
      - text: "Hands-on Ex 9b- Visual Correlation Analysis"
        href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9b.html"
      - text: "Hands-on Ex 9c- Visual Multivariate Analysis with Heatmap"
        href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9c.html"
      - text: "Hands-on Ex 9d- Visual Multivariate Analysis with Parallel Coordinates Plot"
        href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9d.html"
      - text: "Hands-on Ex 9e- Treemap Visualisation with R"
        href: "Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9e.html"
      - text: "Hands-on Ex 10- Information Dashboard Design: R methods"
        href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
    - text: "In-class Ex"
      menu:
      - text: "In-class Ex 1"
        href: "In-class_Ex/In-class_Ex1/In-class_Ex1.html"
      - text: "In-class Ex 2"
        href: "In-class_Ex/In-class_Ex2/In-class_Ex2.html"
      - text: "In-class Ex 4"
        href: "In-class_Ex/In-class_Ex4/In-class_Ex4.html"
      - text: "In-class Ex 5"
        href: "In-class_Ex/In-class_Ex5/In-class_Ex5.html"
      - text: "In-class Ex 5a"
        href: "In-class_Ex/In-class_Ex5/In-class_Ex5a.html"
      - text: "In-class Ex 6"
        href: "In-class_Ex/In-class_Ex6/In-class_Ex6a.html"
      - text: "In-class Ex 6a"
        href: "In-class_Ex/In-class_Ex6/In-class_Ex6a.html"
      - text: "In-class Ex 9"
        href: "In-class_Ex/In-class_Ex9/In-class_Ex9.html"
      - text: "In-class Ex 10"
        href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
    - text: "Take-home Ex"
      menu:
      - text: "Take-home Ex 1"
        href: "Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html"
      - text: "Take-home Ex 2"
        href: "Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html"
      - text: "Take-home Ex 3"
        href: "Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html"
    - text: "Group project"
      menu:
      - text: "Project Website"
        href: "https://takin-g6-2-hk.netlify.app/"
    right:  
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

