---
title: "In-class Ex9"
author: "Jayexx"
date: "June 15, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## Overview

The key learning objective of this hands-on exercise is to plot functional and truthful choropleth maps using appropriate R packages.

## Getting Started

The code chunk below installs and loads various required packages into R environment

```{r}
pacman:: p_load(scatterPlotMatrix, parallelPlot, cluster, factoextra, tidyverse)
```

## Importing Data

```{R}
wine <- read_csv("data/wine_quality.csv")
```
```{r}
ggplot(data = wine,
       aes(x = type)) +
  geom_bar()
```
```{r}
whitewine <- wine %>%
  filter(type == "white") %>%
  select(c(1:11))
```

```{r}
scatterPlotMatrix(whitewine, 
                  corrPlotType = "Text",
                  distribType = 1,
                  rotateTitle = TRUE,
                  width = 900,
                  height = 900
                  )
```

# Compute gap stats

```{r}
set.seed(1234)
gap_stat <- clusGap(whitewine,
                    FUN = kmeans,
                    nstart = 25,
                    K.max = 8,
                    B=50)
print(gap_stat, method = "firstmax")
```

```{r}
set.seed(123)
kmeans4 <- kmeans(whitewine, 4, nstart = 5)
print(kmeans4)
```


```{r}
fviz_cluster(kmeans4, data = whitewine)
```


```{r}
whitewine <- whitewine %>%
  mutate(Cluster = kmeans4$cluster)
```

```{r}
whitewine$Cluster <-
  as_factor(whitewine$Cluster)
```

```{r}
whitewine %>%
  parallelPlot(refColumnDim = "Cluster",
              width = 300,
              height = 250,
              rotateTitle = TRUE)
```







