---
title: "Take-home Ex1"
author: "Jayexx Low"
date: "April 13, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---


## Introduction

There are two major residential property market in Singapore, namely public and private housing. Public housing aims to meet the basic need of the general public with monthly household income less than or equal to S$14,000. For families with monthly household income more than S$14,000, they need to turn to the private residential market.



## Objectives

Assuming the role of a graphical editor of a median company, you are requested to prepare minimum two and maximum three data visualisation to reveal the private residential market and sub-markets of Singapore for the 1st quarter of 2024.

The write-up of the take-home exercise should include but not limited to the followings:

A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared below.

A write-up of not more than 150 words per each data visualisation, describing and discussing the patterns and/or trends reveal by each visualisation prepared.

The key objectives of this exercise are:

-   To perform geovisualisation and analysis of Origin-Destination flows of passenger trips
-   To perform Spatial Interaction Modelling for Origin-Destination flows of passenger trips

## Getting Started

The code chunk below load the following libraries:

-   tidyverse: an amalgamation of libraries for data handling (including ggplot2, dplyr, tidyr, readr, tibble)
-   knitr: for creating html table
-   reshape2: for reshaping functions
-   stplanr:
-   spdep:
-   sfdep: for creating an sf and tidyverse friendly interface as well as for introducing new functionality that is not present in spdep
-   plotly: for interactive plots

```{r}
pacman::p_load(tmap, sf, sp, tidyverse, knitr,  reshape2, stplanr, performance, DT, ggpubr) 
```